# check type and format of the code on PRs

name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check types and format and test
        run: pnpm ci:check

      - name: Report coverage (msw-devtools)
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/msw-devtools

      - name: Report coverage (msw-devtools-server)
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/msw-devtools-server

      - name: Report coverage (core)
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/core
