name: E2E Tests
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build:package

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          VERSION=$(pnpm --filter playground list @playwright/test --json | jq -r '.[0].devDependencies["@playwright/test"].version')
          echo "Playwright version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browser binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright browsers and dependencies
        run: pnpm dlx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Install Playwright dependencies
        run: pnpm dlx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      - name: Run Playwright tests
        run: pnpm e2e:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
